name: mc2dc
version: '${project.version}'
main: eu.zentomomc.mc2dc.Mc2dc
api-version: 1.19
commands:
  tpa:
    description: Teleport to a player
    usage: /tpa <player>
    aliases: [tpahere]
  stopdc:
    description: Stop the Discord bot
    usage: /stopdc
    aliases: [stopdiscord]