name: mc2dc
version: '1.0'
main: eu.zentomomc.mc2dc.Mc2dc
api-version: 1.19
commands:
  tpa:
    description: Teleport to a player
    usage: /tpa <player>
    aliases: [tpahere]
  stopdc:
    description: Stop the Discord bot
    usage: /stopdc
    aliases: [stopdiscord]
  startdc:
    description: Start the Discord bot
    usage: /startdc
    aliases: [startdiscord]
  restartdc:
    description: Restart the Discord bot
    usage: /restartdc
    aliases: [restartdiscord]
