name: Build Jar

on:
  push:
    branches:
      - main

name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Maven Clean and Build
      run: |
        mvn clean
        mvn package

    - name: Upload Jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: mc2dc
        path: autobuild/mc2dc.jar
