name: Build Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn package

    - name: Upload Jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: mc2dc
        path: autobuild/mc2dc.jar
